//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int buy_id { get; set; }
        public int employee_id { get; set; }
        public int medicine_id { get; set; }
        public int supplier_id { get; set; }
        public int count { get; set; }
        public double unit_price { get; set; }
        public System.DateTime date { get; set; }
        public string state { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual medicine medicine { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
