//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_report
    {
        public int sale_id { get; set; }
        public byte[] report_image { get; set; }
    
        public virtual sale sale { get; set; }
    }
}
